version: 2
updates:
  # Enable version updates for Swift
  - package-ecosystem: "swit"
    # Look for `Package.wift` and `Package.resolved` files in the `root` directory
    directory: "./"
    schedule:
      interval: "weekly"

